const ACTIONS = {
    MOVE_LEFT: "MOVE_LEFT",
    MOVE_RIGHT: "MOVE_RIGHT",
    MOVE_TOP: "MOVE_TOP",
    MOVE_BOTTOM: "MOVE_BOTTOM",

    LOOK_LEFT: "LOOK_LEFT",
    LOOK_RIGHT: "LOOK_RIGHT",
    LOOK_TOP: "LOOK_TOP",
    LOOK_BOTTOM: "LOOK_BOTTOM",

    FIRE: "FIRE"
};

const ORIENTATIONS = {
    LEFT: "LEFT",
    RIGHT: "RIGHT",
    TOP: "TOP",
    BOTTOM: "BOTTOM"
};

module.exports = {
    ACTIONS, ORIENTATIONS
}
